package IGU;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import util.BackgroundPanel;

public class FrmCambiarEstCivil extends javax.swing.JFrame {
    
    public FrmCambiarEstCivil() {
    //Crear el panel de fondo ANTES de initComponents
    BackgroundPanel fondo = new BackgroundPanel("/imagenes/civ.png");
    setContentPane(fondo); // el fondo cubre todo el JFrame

    // Inicializar los componentes
    initComponents();

    // Configurar el layout para que el panel principal quede sobre el fondo
    getContentPane().setLayout(new java.awt.BorderLayout());
    fondo.add(EstadoCivil, java.awt.BorderLayout.CENTER); // reemplaza jPanelPrincipal por tu panel real
    EstadoCivil.setOpaque(false); // para que se vea el fondo a través

    //Cargar datos iniciales
    cargarEstadosCiviles();

    //Ajustes finales del JFrame
    pack();
    setLocationRelativeTo(null);
      
   //Cargar los datos del archivo CSV al abrir esta ventana
   insteducativa.GestorDatos.cargar();
    }
    
    private void regresarAlMenu(java.awt.event.ActionEvent evt) {
    VentPrincipal menu = new VentPrincipal(); // Crear instancia del menú principal
    menu.setVisible(true);                     // Mostrar la ventana principal
    this.dispose();                            // Cerrar la ventana actual
    }

    
    private void cargarEstadosCiviles() {
        cmbNuevoEstCiv.removeAllItems();
        cmbNuevoEstCiv.addItem("Soltero(a)");
        cmbNuevoEstCiv.addItem("Casado(a)");
        cmbNuevoEstCiv.addItem("Divorciado(a)");
        cmbNuevoEstCiv.addItem("Viudo(a)");
        cmbNuevoEstCiv.addItem("Unión Libre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EstadoCivil = new javax.swing.JPanel();
        textIdentificacion = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNuevoEstCiv = new javax.swing.JComboBox<>();
        buttonGuardar = new java.awt.Button();
        btbRegresar2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EstadoCivil.setBackground(new java.awt.Color(213, 182, 220));
        EstadoCivil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textIdentificacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EstadoCivil.add(textIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 87, 104, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Identificación");
        EstadoCivil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 87, 127, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nuevo Estado Civil");
        EstadoCivil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 144, -1, 30));

        cmbNuevoEstCiv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbNuevoEstCiv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNuevoEstCiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNuevoEstCivActionPerformed(evt);
            }
        });
        EstadoCivil.add(cmbNuevoEstCiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 146, 141, -1));

        buttonGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonGuardar.setLabel("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });
        EstadoCivil.add(buttonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 241, 80, 35));

        btbRegresar2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btbRegresar2.setLabel("Menú principal");
        btbRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRegresar2ActionPerformed(evt);
            }
        });
        EstadoCivil.add(btbRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 241, -1, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRegresar2ActionPerformed
        regresarAlMenu(evt);
    }//GEN-LAST:event_btbRegresar2ActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
         try {
        // Obtener datos del formulario
        long id = Long.parseLong(textIdentificacion.getText().trim());
        String nuevoEstado = (String) cmbNuevoEstCiv.getSelectedItem();

        // Validar
        if (nuevoEstado == null || nuevoEstado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un nuevo estado civil.");
            return;
        }

        // Intentar cambiar el usuario
        boolean exito = insteducativa.GestorDatos.cambiarEstadoCivil(id, nuevoEstado);

        // Mostrar resultado 
        if (exito) {
            JOptionPane.showMessageDialog(this, 
                "✅ Estado civil actualizado correctamente.");

            // Refrescar la ventana de datos (para ver el cambio reflejado)
            Datos ventanaDatos = new Datos(insteducativa.GestorDatos.getLista());
            ventanaDatos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, 
                "⚠️ No se encontró ninguna persona con esa identificación.");
        }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, ingresa un número de identificación válido.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Error al cambiar el estado civil: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void cmbNuevoEstCivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNuevoEstCivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNuevoEstCivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCambiarEstCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCambiarEstCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCambiarEstCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCambiarEstCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCambiarEstCivil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EstadoCivil;
    private java.awt.Button btbRegresar2;
    private java.awt.Button buttonGuardar;
    private javax.swing.JComboBox<String> cmbNuevoEstCiv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.TextField textIdentificacion;
    // End of variables declaration//GEN-END:variables
}
