package IGU;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import util.BackgroundPanel;

public class VentPrincipal extends javax.swing.JFrame {

    public VentPrincipal() {
        // Primero, crear el panel de fondo ANTES de los componentes
        BackgroundPanel fondo = new BackgroundPanel("/imagenes/fondo.png.png");
        setContentPane(fondo); // <-- El fondo cubre todo el JFrame
        
        initComponents();
        
        // Quitar el color morado del panel para que se vea la imagen
        Fondo.setOpaque(false);

         // Configurar el layout del fondo para que los botones ocupen todo el espacio
        fondo.setLayout(new java.awt.BorderLayout());
        fondo.add(Fondo, java.awt.BorderLayout.CENTER);

        // Establecer el panel con la imagen como contenido principal
        setContentPane(fondo);

        pack();
        setLocationRelativeTo(null);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        Fondo = new javax.swing.JPanel();
        Titulo = new java.awt.Label();
        RegistroPersona = new java.awt.Button();
        CambEstadCivil = new java.awt.Button();
        MatrEstudiante = new java.awt.Button();
        CambFaculProf = new java.awt.Button();
        ModDepAdministrativo = new java.awt.Button();
        ModServiciosVar = new java.awt.Button();
        Regreso = new java.awt.Button();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(204, 204, 255));

        Titulo.setBackground(new java.awt.Color(204, 204, 204));
        Titulo.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        Titulo.setText("   Registro Personal Institución Educativa ODLR");

        RegistroPersona.setBackground(new java.awt.Color(204, 204, 204));
        RegistroPersona.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        RegistroPersona.setLabel("Registrar Persona");
        RegistroPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroPersonaActionPerformed(evt);
            }
        });

        CambEstadCivil.setBackground(new java.awt.Color(204, 204, 204));
        CambEstadCivil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CambEstadCivil.setLabel("Modificar Estado Civil");
        CambEstadCivil.setMinimumSize(new java.awt.Dimension(142, 27));
        CambEstadCivil.setPreferredSize(new java.awt.Dimension(142, 27));
        CambEstadCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambEstadCivilActionPerformed(evt);
            }
        });

        MatrEstudiante.setBackground(new java.awt.Color(204, 204, 204));
        MatrEstudiante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MatrEstudiante.setLabel("Modificar Curso Estudiante ");
        // Conectar botón MatrEstudiante con su ventana
        MatrEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMatricularEstudiante(evt);
            }
        });

        CambFaculProf.setBackground(new java.awt.Color(204, 204, 204));
        CambFaculProf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CambFaculProf.setLabel("Modificar Facultad Profesor");
        CambFaculProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambFaculProfActionPerformed(evt);
            }
        });

        ModDepAdministrativo.setBackground(new java.awt.Color(204, 204, 204));
        ModDepAdministrativo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ModDepAdministrativo.setLabel("Modificar Dependencia Administrativo ");
        ModDepAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModDepAdministrativoActionPerformed(evt);
            }
        });

        ModServiciosVar.setBackground(new java.awt.Color(204, 204, 204));
        ModServiciosVar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ModServiciosVar.setLabel("Modificar Labor Servicios Varios ");
        ModServiciosVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModServiciosVarActionPerformed(evt);
            }
        });

        Regreso.setBackground(new java.awt.Color(204, 204, 204));
        Regreso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Regreso.setLabel("Salir");
        Regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistroPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CambEstadCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatrEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CambFaculProf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModServiciosVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ModDepAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Regreso, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(RegistroPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(CambEstadCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(MatrEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(CambFaculProf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Regreso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ModServiciosVar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(ModDepAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))))
        );

        CambEstadCivil.getAccessibleContext().setAccessibleName("Modificar Estado Civil");
        MatrEstudiante.getAccessibleContext().setAccessibleDescription("");
        Regreso.getAccessibleContext().setAccessibleName("Regresar al menu anterior");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void CambEstadCivilActionPerformed(java.awt.event.ActionEvent evt) {                                             
    FrmCambiarEstCivil frm = new FrmCambiarEstCivil();
    frm.setVisible(true);
    this.dispose();  // opcional, si quiero cerrar la ventana principal
    }
   
    private void RegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresoActionPerformed
    VentPrincipal menu = new VentPrincipal(); // volver al menú principal
    this.dispose();                           // cerrar la ventana actual
    }//GEN-LAST:event_RegresoActionPerformed

    private void CambFaculProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambFaculProfActionPerformed
    FrmCambiarFaculProfe frm = new FrmCambiarFaculProfe();
    frm.setVisible(true);
    this.dispose(); // si quiero cerrar la ventana principal al abrir la nueva
    }//GEN-LAST:event_CambFaculProfActionPerformed

    private void ModDepAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModDepAdministrativoActionPerformed
    FrmModificarDepAdm frm = new FrmModificarDepAdm();
    frm.setVisible(true);
    this.dispose(); // si quiero cerrar la ventana principal al abrir la nueva   
    }//GEN-LAST:event_ModDepAdministrativoActionPerformed

    private void ModServiciosVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModServiciosVarActionPerformed
    FrmCambioLaborSV frm = new FrmCambioLaborSV();
    frm.setVisible(true);
    this.dispose(); // si quiero cerrar la ventana principal al abrir la nueva
    }//GEN-LAST:event_ModServiciosVarActionPerformed

    private void RegistroPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroPersonaActionPerformed
        FrmRegistrarPersona frm = new FrmRegistrarPersona(); // crear el formulario
        frm.setVisible(true);                                // mostrarlo
        this.dispose();                                      // Cierra el menú principal
    }//GEN-LAST:event_RegistroPersonaActionPerformed

    private void abrirMatricularEstudiante(java.awt.event.ActionEvent evt) {
    FrmMatricularEstudiante frm = new FrmMatricularEstudiante();
    frm.setVisible(true);
    this.dispose(); // si quiero cerrar la ventana principal al abrir la nueva
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         // 🔹 Cargar datos desde el archivo CSV antes de abrir la ventana principal
        insteducativa.GestorDatos.cargar();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new VentPrincipal().setVisible(true);
            insteducativa.GestorDatos.cargar();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button CambEstadCivil;
    private java.awt.Button CambFaculProf;
    private javax.swing.JPanel Fondo;
    private java.awt.Button MatrEstudiante;
    private java.awt.Button ModDepAdministrativo;
    private java.awt.Button ModServiciosVar;
    private java.awt.Button RegistroPersona;
    private java.awt.Button Regreso;
    private java.awt.Label Titulo;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
